<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<UserSecretsId>03178d60-8dbc-4f22-89c5-60d2cd1718b8</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
	  <Compile Remove="Extensions\**" />
	  <Content Remove="Extensions\**" />
	  <EmbeddedResource Remove="Extensions\**" />
	  <None Remove="Extensions\**" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Microsoft.Agents.AI.DevUI" Version="1.0.0-preview.260330.1" />
		<PackageReference Include="Microsoft.Agents.AI.Hosting" Version="1.0.0-preview.260330.1" />
		<PackageReference Include="Microsoft.Agents.AI.OpenAI" Version="1.0.0-rc5" />
    <PackageReference Include="Microsoft.Agents.AI.Workflows" Version="1.0.0-rc5" />
      <!--<PackageReference Include="Microsoft.Agents.AI.Workflows.Generators" Version="1.0.0-rc5">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>-->
    <PackageReference Include="Microsoft.Agents.AI.Workflows.Generators" Version="1.0.0-rc5" />
    <!--<PackageReference Include="Microsoft.Extensions.AI.AzureAIInference" Version="10.0.0-preview.1.25559.3" />-->
		<PackageReference Include="Azure.AI.OpenAI" Version="2.9.0-beta.1" />
		<!--<PackageReference Include="Microsoft.Agents.AI.DevUI" Version="1.0.0-preview.260311.1" />-->
		<!--<PackageReference Include="Microsoft.Extensions.AI" />-->
		<!--<PackageReference Include="OllamaSharp" Version="5.4.25" />-->
    <PackageReference Include="Microsoft.Agents.AI.Anthropic" Version="1.0.0-rc5" />
		<PackageReference Include="Spectre.Console" Version="0.54.1-alpha.0.86" />
		<PackageReference Include="Spectre.Console.ImageSharp" Version="0.54.1-alpha.0.86" />
		<PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
	</ItemGroup>

	<ItemGroup>
		<Using Remove="Microsoft.AspNetCore.Routing" />
	</ItemGroup>

	<ItemGroup>
	  <None Update="Data\Input\input.png">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
		<None Update="Data\Input\input.txt">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
		<None Update="Data\Instructions\ExtractorSoloAgent.md">
		  <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Instructions\EntitiesAgent.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Instructions\RelationshipsAgent.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Instructions\MermaidDiagramAgent.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<None Update="Data\Instructions\MermaidReviewerAgent.md">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
	  <None Update="Data\Ontology\entities-ontology.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	  <None Update="Data\Ontology\relationships-ontology.json">
	    <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
	  </None>
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Data\Output\" />
	</ItemGroup>
</Project>
